export enum Role {
    ADMIN = "6",
    USER = "9",
    ANON = "0"
}

export enum Errors {
    UNAUTHORIZED = "UNAUTHORIZED",
    ACCESS_DENIED = "ACCESS_DENIED",
    TOKEN_EXPIRED = "TOKEN_EXPIRED",
    TOKEN_MALFORMED = "TOKEN_MALFORMED",
    NO_TOKEN_PROVIDED = "NO_TOKEN_PROVIDED",
    VALIDATION_ERROR = "VALIDATION_ERROR",
    WRONG_CREDENTIALS = "WRONG_CREDENTIALS",
    UNKNOWN_ERROR = "UNKNOWN_ERROR",
    NOT_FOUND = "NOT_FOUND"
}